export default {
  SET_BUDGET_START: 'budgetApp/SET_BUDGET_START',
  SET_BUDGET_SUCCESS: 'budgetApp/SET_BUDGET_SUCCESS',
  SET_BUDGET_ERROR: 'budgetApp/SET_BUDGET_ERROR',

  GET_BUDGET_START: 'budgetApp/GET_BUDGET_START',
  GET_BUDGET_SUCCESS: 'budgetApp/GET_BUDGET_SUCCESS',
  GET_BUDGET_ERROR: 'budgetApp/GET_BUDGET_ERROR',

  ADD_EXPENSE: 'budgetApp/ADD_EXPENSE',
  DELETE_EXPENSE: 'budgetApp/DELETE_EXPENSE',
  SEARCH_EXPENSE: 'budgetApp/SEARCH_EXPENSE',
};
