export default {
  SET_BUDGET_START: 'budgetApp/SET_BUDGET_START',
  SET_BUDGET_SUCCESS: 'budgetApp/SET_BUDGET_SUCCESS',
  SET_BUDGET_ERROR: 'budgetApp/SET_BUDGET_ERROR',

  GET_BUDGET_START: 'budgetApp/GET_BUDGET_START',
  GET_BUDGET_SUCCESS: 'budgetApp/GET_BUDGET_SUCCESS',
  GET_BUDGET_ERROR: 'budgetApp/GET_BUDGET_ERROR',

  ADD_EXPENSE_START: 'budgetApp/ADD_EXPENSE_START',
  ADD_EXPENSE_SUCCESS: 'budgetApp/ADD_EXPENSE_SUCCESS',
  ADD_EXPENSE_ERROR: 'budgetApp/ADD_EXPENSE_ERROR',

  GET_EXPENSES_START: 'budgetApp/GET_EXPENSES_START',
  GET_EXPENSES_SUCCESS: 'budgetApp/GET_EXPENSES_SUCCESS',
  GET_EXPENSES_ERROR: 'budgetApp/GET_EXPENSES_ERROR',

  DELETE_EXPENSE: 'budgetApp/DELETE_EXPENSE',
  SEARCH_EXPENSE: 'budgetApp/SEARCH_EXPENSE',
};
